# Generated by Django 4.1.7 on 2023-04-26 12:33

from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número de Ficha')),
                ('fecha_ingreso', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Ingreso')),
                ('fecha_productiva', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Etapa Productiva')),
                ('fecha_final', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Salida')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Fichas',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=45, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(max_length=45, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=45, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(max_length=45, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('imagen', models.ImageField(blank=True, default='usuarios/default-user', null=True, upload_to=usuarios.models.get_image_filename)),
                ('rh', models.CharField(choices=[('OP', 'O+'), ('ON', 'O-'), ('AP', 'A+'), ('AN', 'A-'), ('BP', 'B+'), ('BN', 'B-'), ('ABP', 'AB+'), ('ABN', 'AB-')], max_length=3, verbose_name='Factor RH')),
                ('rol', models.CharField(choices=[('I', 'Instructor'), ('A', 'Aprendiz'), ('JA', 'Jefe de Area')], max_length=2, verbose_name='Rol')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extrangería')], max_length=2, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=10, verbose_name='Documento')),
                ('correo_personal', models.EmailField(max_length=50, verbose_name='Correo Personal')),
                ('correo_ins', models.EmailField(max_length=50, verbose_name='Correo Institucional')),
                ('telefono_contacto', models.CharField(max_length=10, verbose_name='Teléfono de Contacto')),
                ('telefono_personal', models.CharField(max_length=10, verbose_name='Teléfono de Personal')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo'), ('2', 'Condicionado')], default='1', max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Usuarios_Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ficha', verbose_name='Ficha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
