# Generated by Django 4.1.7 on 2023-03-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('tipoDocumento', models.CharField(choices=[('1', 'Cédula de Ciudadanía'), ('2', 'Tarjeta de Identidad'), ('3', 'Cédula de Extranjería')], max_length=1, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=45, verbose_name='Documento')),
            ],
        ),
    ]
