# Generated by Django 4.1.7 on 2023-04-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios_Ficha',
        ),
    ]
