# Generated by Django 4.1.7 on 2023-03-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={'verbose_name_plural': 'Fichas'},
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='numero_ficha',
        ),
        migrations.AddField(
            model_name='ficha',
            name='numero',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Ficha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_ins',
            field=models.EmailField(max_length=50, verbose_name='Correo Institucional'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_personal',
            field=models.EmailField(max_length=50, verbose_name='Correo Personal'),
        ),
    ]
