# Generated by Django 4.1.7 on 2023-03-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_ficha_options_remove_ficha_numero_ficha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_final',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_ingreso',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_productiva',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Etapa Productiva'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Nacimiento'),
        ),
    ]
