# Generated by Django 4.1.7 on 2023-04-26 15:57

from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_integrantes_grupo_alter_proyecto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantes',
            name='aprendiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Aprendiz'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='usuarios/default-user.jpeg', null=True, upload_to=usuarios.models.get_image_filename),
        ),
    ]
