# Generated by Django 4.1.7 on 2023-04-19 19:40

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_imagen_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='usuarios/default-user.jpeg', null=True, upload_to=usuarios.models.get_image_filename),
        ),
    ]
