# Generated by Django 4.1.7 on 2023-04-19 21:56

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='usuarios/default-user', null=True, upload_to=usuarios.models.get_image_filename),
        ),
    ]
